export const PLAYLIST_CLIP_EDIT           = 'PLAYLIST_CLIP_EDIT';
export const PLAYLIST_CLIP_CREATE         = 'PLAYLIST_CLIP_CREATE';
export const PLAYLIST_CLIP_DELETE         = 'PLAYLIST_CLIP_DELETE';
export const PLAYLIST_CURRENT_CLIP_UPDATE = 'PLAYLIST_CURRENT_CLIP_UPDATE';

export const VIDEO_URL_UPDATE = 'VIDEO_URL_UPDATE';